ARG VARIANT="14-buster"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

ENV MYSQL_DBNAME=eoloplantsDB
ENV MYSQL_HOST=localhost
ENV MYSQL_PORT=3306
ENV MYSQL_USER=root
ENV MYSQL_PASS=password

ENV RABBIT_USER=guest
ENV RABBIT_PASS=guest
ENV RABBIT_HOST=localhost
ENV RABBIT_PORT=5672
